#!/usr/bin/env bash

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Current theme ---------------------------------------------#

FOREGROUND="#D8DEE9"
BACKGROUND="#1E1E2E"
CURSOR="#D8DEE9"
BLACK="#3B4252"
RED="#BF616A"
GREEN="#A3BE8C"
YELLOW="#EBCB8B"
BLUE="#81A1C1"
MAGENTA="#B48EAD"
CYAN="#88C0D0"
WHITE="#E5E9F0"
ALTBLACK="#4C566A"
ALTRED="#BF616A"
ALTGREEN="#A3BE8C"
ALTYELLOW="#EBCB8B"
ALTBLUE="#81A1C1"
ALTMAGENTA="#B48EAD"
ALTCYAN="#8FBCBB"
ALTWHITE="#ECEFF4"

## Bspwm appearance
CURRENT_BORDER='1'
CURRENT_GAP='6'
CURRENT_SRATIO='0.55'

## Configurations --------------------------------------------#

## Manager Workspaces
bspc monitor -d '' '' '' '' '辶' '' '' '' ''

## Apply bspwm configurations
bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
# bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
# bspc rule -a Alacritty desktop='^1' follow=on focus=on
# bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

## 2 > web (always open web browser on workspace-2)
# bspc rule -a firefox desktop='^2' follow=on focus=on
# bspc rule -a chromium desktop='^2' follow=on focus=on

## 3 > files (always open file manager on workspace-3)
# declare -a files=(Pcmanfm Thunar qBittorrent)
# for i in ${files[@]}; do
   # bspc rule -a $i desktop='^3' follow=on focus=on; done

## 4 > code (always open editors on workspace-4)
# declare -a code=(Geany code-oss)
# for i in ${code[@]}; do
   # bspc rule -a $i desktop='^4' follow=on focus=on; done

## 5 > office and docs (always open office/doc apps on workspace-5)
# declare -a office=(Gucharmap Atril Evince \
# libreoffice-writer libreoffice-calc libreoffice-impress \
# libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
# for i in ${office[@]}; do
   # bspc rule -a $i desktop='^5' follow=on focus=on; done

## 6 > communication (always open communication apps on workspace-6)
# declare -a comm=(Thunderbird TelegramDesktop Hexchat)
# for i in ${comm[@]}; do
   # bspc rule -a $i desktop='^6' follow=on focus=on; done

## 7 > media (always open media apps on workspace-7)
# declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
# for i in ${media[@]}; do
   # bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

## 8 > system (always open system apps on workspace-8)
# bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
# bspc rule -a GParted desktop='^8' follow=on focus=on
# declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
# System-config-printer.py Pavucontrol Exo-helper-1 \
# Xfce4-power-manager-settings)
# for i in ${settings[@]}; do
   # bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

## Always Floating Apps
# declare -a floating=(Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
# Viewnior feh Nm-connection-editor)
# for i in ${floating[@]}; do
   # bspc rule -a $i state=floating follow=on focus=on; done

# bspc rule -a Conky state=floating manage=off
# bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
feh --no-fehbg --bg-fill ~/Data/Nutstore/Pictures/Wallpaper/wallpaper.png

# Start mpd
mpd &

polybar &

picom -b &

dunst &

fcitx5 &

cfw &

nutstore &
